# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_archives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='status',
            field=models.CharField(choices=[('u', 'Undone'), ('p', 'In Progress'), ('d', 'Done')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archive',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='new_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
