# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_archives', '0003_archive_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
