# Generated by Django 2.1.1 on 2018-10-17 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_archives', '0004_archive_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
